# Generated by Django 3.2.7 on 2021-09-09 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('plate_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('model', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ssn', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('ssn', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('is_promoted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='supervisors', serialize=False, to='mainapp.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('method', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('plate_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='mainapp.cars')),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='customer_ssn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='mainapp.customer'),
        ),
        migrations.AddField(
            model_name='cars',
            name='industry_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='mainapp.industry'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('cars_count', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('industry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='mainapp.industry')),
                ('supervisor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='mainapp.supervisor')),
            ],
        ),
    ]
